### ISSUE TITLE
stringifying empty recipes

### ISSUE THREAD

**Issue by pooja335** [eecs394-fall15/stirr#10]
If there are no actions or ingredients in a recipe (banana bread for example), the code is still parsing and stringifying it, making the entry in the database not useful. As a result, I can't add ingredients or actions, because what's in the database right now isn't being parsed and stringified correctly.

**Comment by pooja335** [comment]
this should hopefully be fixed by the changes in explicit-saving branch

**Comment by kapil1garg** [comment]
Taken care of in explicit-branch merge 8deb20e57facfe2968bcab05867c2d3283cf065f
