### ISSUE TITLE
photos are laggy

### ISSUE THREAD

**Issue by pooja335** [eecs394-fall15/stirr#19]
Maybe try making them smaller, but right now they make it almost un-usably laggy

**Comment by kapil1garg** [comment]
The image reduction should mitigate this issue quite a bit. This might be a big issue moving forward if we have a lot of recipes all being loaded at once, so we might need to implement recipe pulls such that it loads 10-20 at a time.

**Comment by kapil1garg** [comment]
App usage seems to show that this issue has been fixed with the image reduction. I think we can close this...thoughts, @pooja335?

**Comment by pooja335** [comment]
yup i agree

**Comment by kapil1garg** [comment]
Closing with b995ddd8fdc29fe8f96357d0b3fcdf5ed2524978
